name: Cypress Tests

on:
  deployment_status

jobs:
  e2e-chrome-tests:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node16.13.0-chrome95-ff94
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress info
        run: npx cypress info

      - name: Node info
        run: node -v

      - name: __e Dir
        run: ls /__e

      - name: Get deployment URL
        id: deployment
        uses: dorshinar/get-deployment-url@master
        timeout-minutes: 5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: "E2E Tests - Chrome"
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
        env:
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEBUG: "cypress:server:args"
          E2E_BASE_URL: ${{ steps.deployment.outputs.deployment }}
